# Generated by Django 6.0.1 on 2026-03-12 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20, unique=True)),
                ('nic_number', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('center_department', models.CharField(max_length=150)),
                ('designation', models.CharField(max_length=150)),
                ('current_designation', models.CharField(max_length=150)),
                ('appointment_date', models.DateField()),
                ('promotion_date', models.DateField(blank=True, null=True)),
                ('pension_date', models.DateField()),
                ('next_increment_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
