# Generated by Django 6.0.1 on 2026-06-16 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_userprofile_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='appointment_date',
            new_name='date_joined',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='nic_number',
            new_name='identity_card_number',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='center_department',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='current_designation',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='email',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='employee_id',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='next_increment_date',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='pension_date',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='promotion_date',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='employee',
            name='center',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='epf_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='employee',
            table='employees',
        ),
    ]
