# Generated by Django 6.0.1 on 2026-06-16 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_rename_appointment_date_employee_date_joined_and_more'),
    ]

    operations = [
    ]
