# Generated by Django 6.0.1 on 2026-06-16 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_auto_20260616_0929'),
    ]

    operations = [
        migrations.CreateModel(
            name='EBSubject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('exam_type', models.CharField(max_length=20)),
                ('subject_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'eb_subjects',
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='epf_no',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='EmployeeEBExam',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('exam_date', models.DateField(blank=True, null=True)),
                ('result', models.CharField(max_length=50)),
                ('marks', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('employee', models.ForeignKey(db_column='epf_no', on_delete=django.db.models.deletion.CASCADE, related_name='eb_exams', to='employee.employee', to_field='epf_no')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.ebsubject')),
            ],
            options={
                'db_table': 'employee_eb_exams',
            },
        ),
        migrations.CreateModel(
            name='EmployeePromotion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('promotion_date', models.DateField()),
                ('promotion_type', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('employee', models.ForeignKey(db_column='epf_no', on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='employee.employee', to_field='epf_no')),
            ],
            options={
                'db_table': 'employee_promotions',
            },
        ),
    ]
