# Generated by Django 6.0.1 on 2026-06-16 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0009_ebsubject_employee_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='employeeebexam',
            unique_together={('employee', 'subject', 'exam_date')},
        ),
    ]
